# Site Settings
title: Github Jagex Portfolio Site
email: u1167937@alumni.hud.ac.uk
description: >
  Github site made with jekyll to show my portfolio for Jagex.
baseurl: ""
url: "https://vhgvvghfhgtydydy.github.io/test/"
